# Generated by Django 5.0 on 2024-10-14 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateField(auto_now=True, verbose_name='modificado em')),
                ('nome', models.CharField(blank=True, max_length=70, verbose_name='Nome')),
                ('rg', models.PositiveIntegerField(blank=True, null=True, verbose_name='RG')),
                ('cpf', models.PositiveIntegerField(blank=True, null=True, verbose_name='CPF')),
                ('nis', models.PositiveIntegerField(blank=True, null=True, verbose_name='NIS')),
                ('telefone', models.PositiveIntegerField(blank=True, null=True, verbose_name='Telefone')),
                ('dt_validade', models.DateField(blank=True, null=True, verbose_name='Data da validade')),
                ('ativo', models.BooleanField(default=False, verbose_name='ativo')),
            ],
            options={
                'verbose_name_plural': 'Titulares',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.CharField(blank=True, max_length=20, verbose_name='Distrito')),
                ('localidade', models.CharField(blank=True, max_length=20, verbose_name='Localidade')),
                ('geolocalizacao', models.IntegerField(blank=True, verbose_name='Geolocalização')),
                ('titular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.titular')),
            ],
            options={
                'verbose_name_plural': 'Endereços',
                'ordering': ('distrito',),
            },
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=70, verbose_name='Nome')),
                ('cpf', models.PositiveIntegerField(blank=True, null=True, verbose_name='CPF')),
                ('parentesco', models.CharField(blank=True, max_length=20, verbose_name='Parentesco')),
                ('idade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade')),
                ('ocupacao', models.CharField(blank=True, max_length=70, verbose_name='Ocupação')),
                ('renda', models.PositiveIntegerField(blank=True, null=True, verbose_name='Renda')),
                ('titular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.titular')),
            ],
            options={
                'verbose_name_plural': 'Dependentes',
                'ordering': ('nome',),
            },
        ),
    ]
